# Nicer names for the printer metrics
groups:
  - name: printer
    rules:
    - record: printer_toner
      expr: prtMarkerSuppliesLevel/prtMarkerSuppliesMaxCapacity{hrDeviceIndex="1",prtMarkerSuppliesIndex="1"}
      labels:
        prtMarkerSuppliesIndex: ''
        hrDeviceIndex: ''

    - record: printer_maintkit
      expr: prtMarkerSuppliesLevel/prtMarkerSuppliesMaxCapacity{hrDeviceIndex="1",prtMarkerSuppliesIndex="2"}
      labels:
        prtMarkerSuppliesIndex: ''
        hrDeviceIndex: ''

    - record: printer_lifetime_pages
      expr: prtMarkerLifeCount{hrDeviceIndex="1",prtMarkerIndex="1"}
      labels:
        prtMarkerIndex: ''
        hrDeviceIndex: ''

    # Some notes on the printer_paper metric:
    # * We don't use tray 1, so don't include them in this record
    # * The tray never goes above "40%" capacity, so divide by 0.4 at the end
    # * We rename the label "prtInputIndex" to "tray" which is clearer
    - record: printer_paper
      expr: |
        label_replace(
          prtInputCurrentLevel/prtInputMaxCapacity{hrDeviceIndex="1", prtInputIndex!="1"}/0.4,
          "tray", "$1", "prtInputIndex", "(.*)"
        )
      labels:
        hrDeviceIndex: ''
        prtInputIndex: ''

    # Error states for the printers, as specified by
    # https://tools.ietf.org/html/rfc1759#section-2.2.13.2.1
    # The snmp_exporter exposes these bitstrings as a label. The ugly (but
    # simplest) way of extracting these bits is by doing regex on the hex
    # string.
    - record: printer_door_open
      # 5th bit
      expr: max(hrPrinterDetectedErrorState{hrDeviceIndex="1",hrPrinterDetectedErrorState=~"0x.[89ABCDEF]"}) without (hrPrinterDetectedErrorState, hrDeviceIndex)

    - record: printer_jammed
      # 6th bit
      expr: max(hrPrinterDetectedErrorState{hrDeviceIndex="1",hrPrinterDetectedErrorState=~"0x.[4567CDEF]"}) without (hrPrinterDetectedErrorState, hrDeviceIndex)

    - record: printer_offline
      # 7th bit
      expr: max(hrPrinterDetectedErrorState{hrDeviceIndex="1",hrPrinterDetectedErrorState=~"0x.[2367ABEF]"}) without (hrPrinterDetectedErrorState, hrDeviceIndex)

    - alert: LowToner
      # Sometimes the printer will randomly report -2 toner and then jump back
      # to the "actual" level.  We take the median over the last 30 minutes to
      # smooth out these spikes.
      expr: quantile_over_time(0.5, printer_toner[30m]) < 0.03
      annotations:
        summary: "Low toner on {{ $labels.instance }}"
        description: "{{ $labels.instance }} toner is at level {{ $value }}, replace it soon!"
    - alert: PrinterDown
      expr: up{job="printer"} == 0
      for: 1m
      annotations:
        summary: "Printer {{ $labels.instance }} is down"
